### ISSUE TITLE
Pretrained Model

### ISSUE THREAD

**Issue by Oscaarjs** [UestcJay/GraphFit#1]
Is there any possibility of adding the weights for an already pre-trained model for testing?

Br

**Comment by UestcJay** [comment]
adding the weights for an already pre-trained model? what is the pre-trained model? In our paper, the input of the model is point  cloud, output is the weights... or you want to obtain the pretrained model?

**Comment by Oscaarjs** [comment]
Thanks for answering and sorry for being unclear. I meant if you have a saved already trained model that you can share. I.e, such that I don't have to train it for 600 epochs to test it out on my own data. That is a ".pth" file. 

Br

**Comment by UestcJay** [comment]
Sorry for the late reply, I will upload the model later, but I don't expect it to be short, because I have been busy with some meaningless things recently, but I suggest that you can use [adafit](https://github.com/Runsong123/AdaFit) or [deepfit](https://github.com/sitzikbs/DeepFit) if you are only testing on your own data, already have a model.

**Comment by UestcJay** [comment]
Sorry for the late reply!  I upload the lastest pretrained model.

**Comment by varunkasi** [comment]
Getting error when testing your pretrained model weights on my data - 

        size mismatch for module.feat.conv3.weight: copying a param with shape torch.Size([256, 128, 1]) from checkpoint, the shape in current model is torch.Size([1024, 128, 1]).
        size mismatch for module.feat.conv3.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([1024]).
        size mismatch for module.feat.bn3.weight: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([1024]).
        size mismatch for module.feat.bn3.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([1024]).
        size mismatch for module.feat.bn3.running_mean: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([1024]).
        size mismatch for module.feat.bn3.running_var: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([1024]).
        size mismatch for module.conv1.weight: copying a param with shape torch.Size([512, 1472, 1]) from checkpoint, the shape in current model is torch.Size([512, 1088, 1]).
