### ISSUE TITLE
Getting error when testing your pretrained model weights on my data

### ISSUE THREAD

**Issue by varunkasi** [UestcJay/GraphFit#2]
Getting error when testing your pretrained model weights on my data - 

        size mismatch for module.feat.conv3.weight: copying a param with shape torch.Size([256, 128, 1]) from checkpoint, the shape in current model is torch.Size([1024, 128, 1]).
        size mismatch for module.feat.conv3.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([1024]).
        size mismatch for module.feat.bn3.weight: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([1024]).
        size mismatch for module.feat.bn3.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([1024]).
        size mismatch for module.feat.bn3.running_mean: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([1024]).
        size mismatch for module.feat.bn3.running_var: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([1024]).
        size mismatch for module.conv1.weight: copying a param with shape torch.Size([512, 1472, 1]) from checkpoint, the shape in current model is torch.Size([512, 1088, 1]).

_Originally posted by @varunkasi in https://github.com/UestcJay/GraphFit/issues/1#issuecomment-1371669501_

I think the error is due to the way DeepFit function is being imported into the test_n_est_ms.py. If you run testing after training, I think this error will not occur. However, if we do only testing, we should import GraphFit_ms as DeepFit. A good reference would be to see how it is done in the train_n_est_ms.py file.

**Comment by UestcJay** [comment]
Very sorry for this, I will fix this later..
