### ISSUE TITLE
您好！请问为什么找不到DeepFit.py。

### ISSUE THREAD

**Issue by Russ-Yan** [UestcJay/GraphFit#3]
FileNotFoundError: [Errno 2] No such file or directory: './log/GraphFit\\DeepFit.py'

**Comment by UestcJay** [comment]
It is better to train the model yourself，  if you are going to use the provided model， you can organize the log folder as:

```
├──log/
    ├──GraphFit/
             ├──DeepFit.py   #rename GraphFit_ms.py
             ├──trained_models/
                   ├──GraphFit_k500_n3_model_599.pth
                   ├──GraphFit_k500_n3_params.pth
```
I will fix this error later...

**Comment by Russ-Yan** [comment]
Thank you very much for your reply. This is really helpful for me. 
BTW, there is a typo here: you spelled graphfit as graphfit in the filename ：）

**Comment by Russ-Yan** [comment]
Thank you very much for your reply. This is really helpful for me. 
BTW, there is a typo here: you spelled graphFit as grapgFit in the filename(GraphFit_k500_n3_599.pth).

**Comment by UestcJay** [comment]
many thanks!
